### ISSUE TITLE
states_memory를 np.vstack으로 묶었을 경우 states의 형태

### ISSUE THREAD

**Issue by ByungSunBae** [kkweon/PAAC-in-Tensorflow#3]
안녕하세요. 애자일소다의 배병선이라고 합니다.

현재 저는 PAAC를 파이토치로 구현했는데, 제가 구현한 것과 논문의 내용이 약간 달라서 경모님의 코드를 참고하던중 궁금한 점이 있어서 이렇게 문의를 드립니다.

train.py 에서 train 함수의 docstring을 살펴보니 states의 형태가 [환경의 갯수, 타임스텝, 높이, 너비, 채널수] 로 기록이 되어있는데, run_episodes에서 for문 부분만 가지고 실행시킨 후 states_memory를 np.vstack을 이용해서 해보니 [5, 10, 80, 80, 1]으로 예상했는데 [50, 80, 80, 1]이 나오더라구요. 

물론 vstack을 실행시켰을 때, 경모님 코드 그대로 복붙해서 실행했습니다.(저는 t_max=10, 환경의 갯수를 5로 셋팅하였습니다.)

궁금한 점은 2가지 입니다.

1) [5, 10, 80, 80, 1]으로 나오려면 np.expand_dims를 axis=0로 argument를 셋팅하여 한번 더 적용해야하지 않나요? (제가 잘못봤을 수도 있습니다.)

2) 제가 구현한 방식은 각 환경별로 [게임실행 + 모델 파라미터 업데이트]를 했습니다. 다시말해, 

  - 1번째 환경에 대해서 1개의 에피소드가 끝날때까지 t_max만큼 게임실행 후 모델 파라미터 업데이트
  => 2번째 환경에 대해서 1개의 에피소드가 끝날때까지 t_max만큼 게임실행 후 모델 파라미터 업데이트
  => ...
  => 10번째 환경에 대해서 1개의 에피소드가 끝날때까지 t_max만큼 게임실행 후 모델 파라미터 업데이트
  이런식으로 했는데 학습은 되더군요.. 제것은 t_max를 주기로 업데이트가 되는 건데 논문에서 나온걸 보니 (환경의 갯수 * t_max)를 주기로 업데이트 한다고 나와있더라구요. 별차이가 없을까요?

감사합니다.

**Comment by kkweon** [comment]
1. 네 말씀하신게 맞습니다. :smile: 예전에 만들때 여러가지로 막 가져다 붙이다 보니 docstring은 변하지 않았네요. 잘못된건 docstring입니다. (env * time_step, H, W, C)  => (?, H, W, C)  상태로 네트워크에 들어가게 되있습니다. 어쨌든 docstring은 수정해야되는걸 까먹고 냅두고 있었는데 감사합니다.

2. 학습은 원래 하나의 환경에서도 학습이 되기 때문에 되는거야 당연한 것인데 해당 논문이나 A3C의 주요 포인트는 여러 환경의 데이터를 받아서 업데이트한다는게 적절히 주 목적이었기 때문에 실제 논문 구현하고 주요 포인트가 달라지는 것 같네요.

말씀하신건
```
1번째 환경 => 관측 데이터 => 업데이트  => 2번째 환경 => 관측 데이터 => 업데이트
```
이건 결국 하나의 env로만 학습한거랑 차이가 없어서 asynchronous로 보기는 어려울 것 같네요.

논문에서는

```
1번째 환경 => 데이터  ------+
2번째 환경 => 데이터  ------+--------> 모아서 학습
3번째 환경 => 데이터   -----+
```
이러면 실제 학습을 할때 여러 경우의 수를 이미 관측하고 업데이트를 하는 것이기 때문에 outlier에 좀더 강할 것 같네요.

**Comment by ByungSunBae** [comment]
아아~~ 이제서야 이해가 되는군요.

너무 구현에만 집중하다보니 논문의 주목적을 생각하지 못했습니다.

또 배워가네요.ㅎㅎㅎ 감사합니다!!

**Comment by kkweon** [comment]
저야말로 많이 배우고 있습니다. 감사합니다 :smiley:
